/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityAvatar: typeof import('./components/onboarding/avatars/ActivityAvatar.vue')['default']
    ActivityLevelScreen: typeof import('./components/onboarding/screens/ActivityLevelScreen.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BodyTypeScreen: typeof import('./components/onboarding/screens/BodyTypeScreen.vue')['default']
    DefaultAvatar: typeof import('./components/onboarding/avatars/DefaultAvatar.vue')['default']
    FitnessExperienceScreen: typeof import('./components/onboarding/screens/FitnessExperienceScreen.vue')['default']
    FoodRegisterModal: typeof import('./components/home/FoodRegisterModal.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NameSexScreen: typeof import('./components/onboarding/screens/NameSexScreen.vue')['default']
    OnboardingWizard: typeof import('./components/onboarding/OnboardingWizard.vue')['default']
    PhotoCaptureScreen: typeof import('./components/onboarding/screens/PhotoCaptureScreen.vue')['default']
    ReasonScreen: typeof import('./components/onboarding/screens/ReasonScreen.vue')['default']
    Resumen: typeof import('./components/home/Resumen.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserAvatar: typeof import('./components/home/UserAvatar.vue')['default']
    WeightRegisterModal: typeof import('./components/home/WeightRegisterModal.vue')['default']
    WeightScreen: typeof import('./components/onboarding/screens/WeightScreen.vue')['default']
    WelcomeScreen: typeof import('./components/onboarding/screens/WelcomeScreen.vue')['default']
  }
}
